name:                Thcheme
version:             0.2.0.0
github:              "JKTKops/Thcheme"
license:             BSD3
author:              "Max Kopinsky"
maintainer:          "zerglingk9012@gmail.com"
copyright:           "2019 Max Kopinsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JKTKops/Thcheme#readme>

default-extensions:
- FlexibleContexts
- LambdaCase

# At some point, we should specify which dependencies
# are being used where.
dependencies:
- base >= 4.7 && < 5
- array # needed by Happy
- case-insensitive
- containers
- hashtables
- haskeline
- monad-loops
- mtl
- random
- transformers
- union-find
- unordered-containers
- vector

data-files:
  - lib/**/*.scm
  - lib/**/*.exp

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-orphans

executables:
  thcheme:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    dependencies:
    - Thcheme

tests:
  thcheme-test:
    main:                Spec.hs
    source-dirs:         test
    # we used to run threaded tests, but threading the tests
    # breaks the expander, so we no longer do that.
    # -threaded
    dependencies:
    - Thcheme
    - tasty
    - tasty-hunit
    - smallcheck
    - tasty-smallcheck
    - QuickCheck
    - tasty-quickcheck
